global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1
scrape_configs:
- job_name: reactions_storage
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - reactions_storage:8080
  metric_relabel_configs:
  - source_labels: ['url']
    regex: '([^?#]*).*'
    replacement: '${1}'
    target_label: path
  - source_labels: ['method', 'path']
    separator: '_'
    target_label: method_path
- job_name: reactions_storage_vm
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - 158.160.36.67:8080
  metric_relabel_configs:
  - source_labels: ['url']
    regex: '([^?#]*).*'
    replacement: '${1}'
    target_label: path
  - source_labels: ['method', 'path']
    separator: '_'
    target_label: method_path
- job_name: pushgateway
  honor_labels: true
  honor_timestamps: true
  static_configs:
  - targets:
    - prometheus_pushgateway:9091
  metric_relabel_configs:
  - source_labels: ['method', 'path']
    separator: '_'
    target_label: method_path
- job_name: node_exporter
  static_configs:
  - targets:
    - prometheus_node_exporter:9100
  metric_relabel_configs:
      - source_labels: [ __name__ ]
        target_label: __name__
        regex: '(.*)'
        action: replace
        replacement: localhost_${1}