#!/usr/bin/env bash

set -ex

CMD_DIR=$(dirname "${BASH_SOURCE[0]}")

set +x
source $CMD_DIR/common/env_vars db
set -x

$CMD_DIR/db_deploy
$CMD_DIR/rs_deploy
$CMD_DIR/monitoring_deploy
$CMD_DIR/sim_deploy
