#!/usr/bin/env bash

set -ex

CMD_DIR=$(dirname "${BASH_SOURCE[0]}")

set +x
source $CMD_DIR/common/env_vars sim
set -x

ssh -o "StrictHostKeyChecking no" $SSH_USER@$SSH_HOST "sudo docker-compose -f $REMOTE_WORKDIR/docker-compose.yaml stop simulation"
