#!/usr/bin/env python3
import sys
import yaml


def main():
    unicode_reactions = sys.argv[1]
    data = []
    for r in unicode_reactions:
        data.append({
            'id': r,
            'type': 'unicode',
            'code': r,
        })
    yaml.dump(data, sys.stdout, allow_unicode=True, sort_keys=False)


if __name__ == '__main__':
    main()
