#!/usr/bin/env bash

# kportpid-- kill pid that uses given port

function fport() {
    lsof -n -i :$1
}

function fportpids() {
    pids="$(fport $1 | tail -n +2 | awk '{print $2}')" # quotes are needed to preserve new lines as they are special characters
    echo "$pids"
}

pids="$(fportpids $@)"
if [[ ! -z "$pids" ]]; then
    echo "$pids" | xargs -n 1 kill
fi
