#!/usr/bin/env bash

function fport() {
    lsof -n -i :$1
}

function fportpid() {
    pid=$(fport $1 | tail -n +2 | awk '{print $2}')
    echo $pid
}

pid=$(fportpid $@)
if [ ! -z $pid ]; then kill $pid; fi
