#!/usr/bin/env bash

set -e

function sql() {
    PGPASSWORD=$POSTGRES_PASSWORD psql -h $POSTGRES_HOST -p $POSTGRES_PORT -U $POSTGRES_USER -d $POSTGRES_DB -f $1
    return $?
}

sql devtools/sql/destroy_db.sql
sql sql/init_configuration_storage.sql
sql sql/init_reactions_storage.sql
