#!/usr/bin/env bash

set -ex

CMD_DIR=$(dirname "${BASH_SOURCE[0]}")

set +x
source $CMD_DIR/common/env_vars sim
set -x

$CMD_DIR/common/build_and_push sim

$CMD_DIR/common/scp_bundle sim

ssh -o "StrictHostKeyChecking no" $SSH_USER@$SSH_HOST "mkdir -p $REMOTE_WORKDIR/deploy/docker-compose"
scp -r deploy/vm/simulation $SSH_USER@$SSH_HOST:$REMOTE_WORKDIR/deploy/docker-compose/

$CMD_DIR/common/setup_vm sim

ssh -o "StrictHostKeyChecking no" $SSH_USER@$SSH_HOST "sudo docker-compose -f $REMOTE_WORKDIR/docker-compose.yaml pull $SERVICES"
ssh -o "StrictHostKeyChecking no" $SSH_USER@$SSH_HOST "sudo docker-compose -f $REMOTE_WORKDIR/docker-compose.yaml down"
ssh -o "StrictHostKeyChecking no" $SSH_USER@$SSH_HOST "sudo docker-compose -f $REMOTE_WORKDIR/docker-compose.yaml up -d prometheus_node_exporter"
