global:
  scrape_interval: 30s
  scrape_timeout: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1

# NOTE: uncomment scrape_configs and fill addresses for prometheus to reach other components
# scrape_configs:
# - job_name: reactions_storage
#   scrape_timeout: 30s
#   honor_timestamps: true
#   metrics_path: /metrics
#   scheme: http
#   static_configs:
#   - targets:
#     # >>> YOUR ADDRESS HERE <<<
#     - 10.128.0.30:8080
#   metric_relabel_configs:
#   - source_labels: ['url']
#     regex: '([^?#]*).*'
#     replacement: '${1}'
#     target_label: path
#   - source_labels: ['method', 'path']
#     separator: '_'
#     target_label: method_path
    
# - job_name: pushgateway
#   honor_labels: true
#   honor_timestamps: true
#   static_configs:
#   - targets:
#     - prometheus_pushgateway:9091
#   metric_relabel_configs:
#   - source_labels: ['method', 'path']
#     separator: '_'
#     target_label: method_path

# - job_name: reactions_storage_node_exporter
#   static_configs:
#   - targets:
#     # >>> YOUR ADDRESS HERE <<<
#     - 10.128.0.30:9100
#   metric_relabel_configs:
#       - source_labels: [ __name__ ]
#         target_label: __name__
#         regex: '(.*)'
#         action: replace
#         replacement: rs_${1}

# - job_name: db_node_exporter
#   static_configs:
#   - targets:
#     # >>> YOUR ADDRESS HERE <<<
#     - 10.128.0.3:9100
#   metric_relabel_configs:
#       - source_labels: [ __name__ ]
#         target_label: __name__
#         regex: '(.*)'
#         action: replace
#         replacement: db_${1}

# - job_name: monitoring_node_exporter
#   honor_timestamps: true
#   static_configs:
#   - targets:
#     # >>> YOUR ADDRESS HERE <<<
#     - 172.17.0.1:9100
#   metric_relabel_configs:
#       - source_labels: [ __name__ ]
#         target_label: __name__
#         regex: '(.*)'
#         action: replace
#         replacement: monitoring_${1}

# - job_name: simulation_node_exporter
#   static_configs:
#   - targets:
#     # >>> YOUR ADDRESS HERE <<<
#     - 10.128.0.9:9100
#   metric_relabel_configs:
#       - source_labels: [ __name__ ]
#         target_label: __name__
#         regex: '(.*)'
#         action: replace
#         replacement: sim_${1}
