{
 "title": "Reactions Storage",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Server - Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GET /reactions - Latency (p95)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.95,\n    sum(\n      rate(\n        gin_request_duration_seconds_v2_bucket{method=\"GET\",path=\"/reactions\"}[1m]\n      )\n    ) by (le)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "POST /reactions - Latency (p95)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.95,\n    sum(\n      rate(\n        gin_request_duration_seconds_v2_bucket{method=\"POST\",path=\"/reactions\"}[1m]\n      )\n    ) by (le)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DELETE /reactions - Latency (p95)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.95,\n    sum(\n      rate(\n        gin_request_duration_seconds_v2_bucket{method=\"DELETE\",path=\"/reactions\"}[1m]\n      )\n    ) by (le)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SQL - Latency (p95)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.95,\n    sum(\n      rate(\n        gin_sql_query_duration_seconds_bucket[1m]\n      )\n    ) by (le)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error RPS (avg)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  (rate(gin_requests_total{code=~\"4[0-9]{2}\"}[$__rate_interval]) or on() vector(0)) + \n  (rate(gin_requests_total{code=~\"5[0-9]{2}\"}[$__rate_interval]) or on() vector(0))\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total RPS (avg)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(gin_requests_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client Error RPS (avg)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((rate(rs_client_requests_total{code=~\"5[0-9]{2}|\"}[$__rate_interval]) + rate(rs_client_requests_total{has_error=\"true\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Total RPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by (code) (rate(gin_requests_total[1m]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 7, "y": 14 },
   "targets": [
    {
     "expr": "sum by (method_path) (rate(gin_requests_total{code=~\"2[0-9]{2}\"}[1m]))",
     "legendFormat": "{{method_path}}"
    }
   ]
  },
  {
   "title": "ERROR RPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "sum by (method_path) (rate(gin_requests_total{code=~\"4[0-9]{2}\"}[1m]))",
     "legendFormat": "{{method_path}}"
    }
   ]
  },
  {
   "title": "Latency (p10)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.10,\n    sum(\n      rate(\n        gin_request_duration_seconds_v2_bucket[1m]\n      )\n    ) by (le)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP 1xx",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(gin_requests_total{code=~\"1[0-9]{2}\"}[1m]))/sum(increase(gin_requests_total[1m])) *100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP 2xx",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 7, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(gin_requests_total{code=~\"2[0-9]{2}\"}[1m]))/sum(increase(gin_requests_total[1m])) *100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP 3xx",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(gin_requests_total{code=~\"3[0-9]{2}\"}[1m]))/sum(increase(gin_requests_total[1m])) *100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP 4xx",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 14, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(gin_requests_total{code=~\"4[0-9]{2}\"}[1m]))/sum(increase(gin_requests_total[1m])) *100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP 5xx",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 17, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(gin_requests_total{code=~\"5[0-9]{2}\"}[1m]))/sum(increase(gin_requests_total[1m])) *100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency (p99)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.99,\n    sum(\n      rate(\n        gin_request_duration_seconds_v2_bucket[1m]\n      )\n    ) by (le)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SQL Total RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 27 },
   "targets": [
    { "expr": "rate(gin_sql_query_count[1m])", "legendFormat": "total" }
   ]
  },
  {
   "title": "Latency (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 7, "y": 27 },
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.95,\n    sum(\n      rate(\n        gin_request_duration_seconds_v2_bucket[1m]\n      )\n    ) by (le, method_path)\n)",
     "legendFormat": "{{method_path}}"
    }
   ]
  },
  {
   "title": "SQL Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "targets": [
    {
     "expr": "histogram_quantile(\n    0.99,\n    sum(\n      rate(\n        gin_sql_query_duration_seconds_bucket[1m]\n      )\n    ) by (le)\n)",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(\n    0.95,\n    sum(\n      rate(\n        gin_sql_query_duration_seconds_bucket[1m]\n      )\n    ) by (le)\n)",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(\n    0.10,\n    sum(\n      rate(\n        gin_sql_query_duration_seconds_bucket[1m]\n      )\n    ) by (le)\n)",
     "legendFormat": "p10"
    },
    {
     "expr": "histogram_quantile(\n    0.90,\n    sum(\n      rate(\n        gin_sql_query_duration_seconds_bucket[1m]\n      )\n    ) by (le)\n)",
     "legendFormat": "p90"
    }
   ]
  },
  {
   "title": "Client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total RPS",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "sum by (code) (rate(rs_client_requests_total[1m]))",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "OK RPS",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 36 },
     "targets": [
      {
       "expr": "sum by (method_path) (rate(rs_client_requests_total{code=~\"2[0-9]{2}\"}[1m]))",
       "legendFormat": "{{method_path}}"
      }
     ]
    },
    {
     "title": "ERROR RPS",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 36 },
     "targets": [
      {
       "expr": "sum by (method_path) (\n    (rate(rs_client_requests_total{code=~\"4[0-9]{2}|\"}[1m]) or on() vector(0)) + \n    (rate(rs_client_requests_total{code=~\"5[0-9]{2}|\"}[1m]) or on() vector(0)) + \n    (rate(rs_client_requests_total{has_error=\"true\"}[1m]) or on() vector(0))\n)",
       "legendFormat": "{{method_path}}"
      }
     ]
    },
    {
     "title": "Latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 36 },
     "targets": [
      {
       "expr": "histogram_quantile(\n    0.99,\n    sum(\n      rate(\n        rs_client_request_duration_seconds_bucket[1m]\n      )\n    ) by (le)\n)",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(\n    0.95,\n    sum(\n      rate(\n        rs_client_request_duration_seconds_bucket[1m]\n      )\n    ) by (le)\n)",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(\n    0.10,\n    sum(\n      rate(\n        rs_client_request_duration_seconds_bucket[1m]\n      )\n    ) by (le)\n)",
       "legendFormat": "p10"
      }
     ]
    }
   ]
  },
  {
   "title": "GET /reactions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total RPS",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 37 },
     "targets": [
      {
       "expr": "sum by (code) (rate(gin_requests_total{method_path=\"GET_/reactions\"}[1m]))",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "OK RPS",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 9, "x": 7, "y": 37 },
     "targets": [
      {
       "expr": "sum by (code) (rate(gin_requests_total{method_path=\"GET_/reactions\", code=~\"2[0-9]{2}\"}[1m]))",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "ERROR RPS",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 37 },
     "targets": [
      {
       "expr": "sum by (method_path) (rate(gin_requests_total{method_path=\"GET_/reactions\", code=~\"4[0-9]{2}\"}[1m]))",
       "legendFormat": "{{method_path}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GET /reactions (DEBUG)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Acquire Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 45 },
     "targets": [
      {
       "expr": "histogram_quantile(\n    0.99,\n    sum(\n      rate(\n        gin_GET_reactions__acquire_bucket[1m]\n      )\n    ) by (le)\n)",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(\n    0.95,\n    sum(\n      rate(\n        gin_GET_reactions__acquire_bucket[1m]\n      )\n    ) by (le)\n)",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(\n    0.10,\n    sum(\n      rate(\n        gin_GET_reactions__acquire_bucket[1m]\n      )\n    ) by (le)\n)",
       "legendFormat": "p10"
      },
      {
       "expr": "histogram_quantile(\n    0.90,\n    sum(\n      rate(\n        gin_GET_reactions__acquire_bucket[1m]\n      )\n    ) by (le)\n)",
       "legendFormat": "p90"
      }
     ]
    },
    {
     "title": "GetEntityReactionsCount Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 45 },
     "targets": [
      {
       "expr": "histogram_quantile(\n    0.99,\n    sum(\n      rate(\n        gin_GET_reactions__get_entity_reactions_count_bucket[1m]\n      )\n    ) by (le)\n)",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(\n    0.95,\n    sum(\n      rate(\n        gin_GET_reactions__get_entity_reactions_count_bucket[1m]\n      )\n    ) by (le)\n)",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(\n    0.10,\n    sum(\n      rate(\n        gin_GET_reactions__get_entity_reactions_count_bucket[1m]\n      )\n    ) by (le)\n)",
       "legendFormat": "p10"
      },
      {
       "expr": "histogram_quantile(\n    0.90,\n    sum(\n      rate(\n        gin_GET_reactions__get_entity_reactions_count_bucket[1m]\n      )\n    ) by (le)\n)",
       "legendFormat": "p90"
      }
     ]
    },
    {
     "title": "GetUniqEntityUserReactions Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 45 },
     "targets": [
      {
       "expr": "histogram_quantile(\n    0.99,\n    sum(\n      rate(\n        gin_GET_reactions__get_uniq_entity_user_reactions_bucket[1m]\n      )\n    ) by (le)\n)",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(\n    0.95,\n    sum(\n      rate(\n        gin_GET_reactions__get_uniq_entity_user_reactions_bucket[1m]\n      )\n    ) by (le)\n)",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(\n    0.10,\n    sum(\n      rate(\n        gin_GET_reactions__get_uniq_entity_user_reactions_bucket[1m]\n      )\n    ) by (le)\n)",
       "legendFormat": "p10"
      },
      {
       "expr": "histogram_quantile(\n    0.90,\n    sum(\n      rate(\n        gin_GET_reactions__get_uniq_entity_user_reactions_bucket[1m]\n      )\n    ) by (le)\n)",
       "legendFormat": "p90"
      }
     ]
    }
   ]
  },
  {
   "title": "POST /reactions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total RPS",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 39 },
     "targets": [
      {
       "expr": "sum by (code) (rate(gin_requests_total{method_path=\"POST_/reactions\"}[1m]))",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "OK RPS",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 9, "x": 7, "y": 39 },
     "targets": [
      {
       "expr": "sum by (code) (rate(gin_requests_total{method_path=\"POST_/reactions\", code=~\"2[0-9]{2}\"}[1m]))",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "ERROR RPS",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 39 },
     "targets": [
      {
       "expr": "sum by (method_path) (rate(gin_requests_total{method_path=\"POST_/reactions\", code=~\"4[0-9]{2}\"}[1m]))",
       "legendFormat": "{{method_path}}"
      }
     ]
    }
   ]
  },
  {
   "title": "POST /reactions (DEBUG)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Acquire Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 62 },
     "targets": [
      {
       "expr": "histogram_quantile(\n    0.99,\n    sum(\n      rate(\n        gin_POST_reactions__acquire_bucket[1m]\n      )\n    ) by (le)\n)",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(\n    0.95,\n    sum(\n      rate(\n        gin_POST_reactions__acquire_bucket[1m]\n      )\n    ) by (le)\n)",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(\n    0.10,\n    sum(\n      rate(\n        gin_POST_reactions__acquire_bucket[1m]\n      )\n    ) by (le)\n)",
       "legendFormat": "p10"
      },
      {
       "expr": "histogram_quantile(\n    0.90,\n    sum(\n      rate(\n        gin_POST_reactions__acquire_bucket[1m]\n      )\n    ) by (le)\n)",
       "legendFormat": "p90"
      }
     ]
    },
    {
     "title": "GetNamespace Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 62 },
     "targets": [
      {
       "expr": "histogram_quantile(\n    0.99,\n    sum(\n      rate(\n        gin_POST_reactions__get_namespace_bucket[1m]\n      )\n    ) by (le)\n)",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(\n    0.95,\n    sum(\n      rate(\n        gin_POST_reactions__get_namespace_bucket[1m]\n      )\n    ) by (le)\n)",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(\n    0.10,\n    sum(\n      rate(\n        gin_POST_reactions__get_namespace_bucket[1m]\n      )\n    ) by (le)\n)",
       "legendFormat": "p10"
      },
      {
       "expr": "histogram_quantile(\n    0.90,\n    sum(\n      rate(\n        gin_POST_reactions__get_namespace_bucket[1m]\n      )\n    ) by (le)\n)",
       "legendFormat": "p90"
      }
     ]
    },
    {
     "title": "AddUserReaction Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 62 },
     "targets": [
      {
       "expr": "histogram_quantile(\n    0.99,\n    sum(\n      rate(\n        gin_POST_reactions__add_user_reaction_bucket[1m]\n      )\n    ) by (le)\n)",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(\n    0.95,\n    sum(\n      rate(\n        gin_POST_reactions__add_user_reaction_bucket[1m]\n      )\n    ) by (le)\n)",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(\n    0.10,\n    sum(\n      rate(\n        gin_POST_reactions__add_user_reaction_bucket[1m]\n      )\n    ) by (le)\n)",
       "legendFormat": "p10"
      },
      {
       "expr": "histogram_quantile(\n    0.90,\n    sum(\n      rate(\n        gin_POST_reactions__add_user_reaction_bucket[1m]\n      )\n    ) by (le)\n)",
       "legendFormat": "p90"
      }
     ]
    }
   ]
  },
  {
   "title": "DELETE /reactions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total RPS",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 71 },
     "targets": [
      {
       "expr": "sum by (code) (rate(gin_requests_total{method_path=\"DELETE_/reactions\"}[1m]))",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "OK RPS",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 9, "x": 7, "y": 71 },
     "targets": [
      {
       "expr": "sum by (code) (rate(gin_requests_total{method_path=\"DELETE_/reactions\", code=~\"2[0-9]{2}\"}[1m]))",
       "legendFormat": "{{code}}"
      }
     ]
    },
    {
     "title": "ERROR RPS",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 71 },
     "targets": [
      {
       "expr": "sum by (method_path) (rate(gin_requests_total{method_path=\"DELETE_/reactions\", code=~\"4[0-9]{2}\"}[1m]))",
       "legendFormat": "{{method_path}}"
      }
     ]
    }
   ]
  },
  {
   "title": "DELETE /reactions (DEBUG)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Acquire Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 79 },
     "targets": [
      {
       "expr": "histogram_quantile(\n    0.99,\n    sum(\n      rate(\n        gin_DELETE_reactions__acquire_bucket[1m]\n      )\n    ) by (le)\n)",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(\n    0.95,\n    sum(\n      rate(\n        gin_DELETE_reactions__acquire_bucket[1m]\n      )\n    ) by (le)\n)",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(\n    0.10,\n    sum(\n      rate(\n        gin_DELETE_reactions__acquire_bucket[1m]\n      )\n    ) by (le)\n)",
       "legendFormat": "p10"
      },
      {
       "expr": "histogram_quantile(\n    0.90,\n    sum(\n      rate(\n        gin_DELETE_reactions__acquire_bucket[1m]\n      )\n    ) by (le)\n)",
       "legendFormat": "p90"
      }
     ]
    },
    {
     "title": "RemoveUserReaction Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 79 },
     "targets": [
      {
       "expr": "histogram_quantile(\n    0.99,\n    sum(\n      rate(\n        gin_DELETE_reactions__remove_user_reaction_bucket[1m]\n      )\n    ) by (le)\n)",
       "legendFormat": "p99"
      },
      {
       "expr": "histogram_quantile(\n    0.95,\n    sum(\n      rate(\n        gin_DELETE_reactions__remove_user_reaction_bucket[1m]\n      )\n    ) by (le)\n)",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(\n    0.10,\n    sum(\n      rate(\n        gin_DELETE_reactions__remove_user_reaction_bucket[1m]\n      )\n    ) by (le)\n)",
       "legendFormat": "p10"
      },
      {
       "expr": "histogram_quantile(\n    0.90,\n    sum(\n      rate(\n        gin_DELETE_reactions__remove_user_reaction_bucket[1m]\n      )\n    ) by (le)\n)",
       "legendFormat": "p90"
      }
     ]
    }
   ]
  }
 ]
}