gin:
  general:
    mode: release
    trusted_proxies: []
  middlewares:
    logger:
      enabled: true
    recovery:
      enabled: true
    prometheus:
      enabled: true
      metrics_path: /metrics
      metrics:
        gin:
          enabled: true
        sql:
          enabled: true
        debug:
          enabled: true
  handlers:
    debug:
      pprof:
        enabled: true
        path_prefix: /debug/pprof
      mem_usage:
        enabled: true
        path: /debug/sys/mem

pg:
  pool:
    min_conns: 5
    max_conns: 490
    max_conn_lifetime_jitter_s: 1
