#!/usr/bin/env python3
import argparse
import logging
import os
import requests
import sys
import yaml
from pathlib import Path


logging.basicConfig(
    level=logging.INFO,
)


def parse_args():
    parser = argparse.ArgumentParser(description='Apply env to given RS service')
    parser.add_argument('env-name', choices=['fake', 'load-test'], help='Choose env to apply')
    return parser.parse_args()


def main():
    env_name = sys.argv[1]
    env_dir = Path(__file__).parent / env_name
    configuration = {}
    with (env_dir / 'reactions.yaml').open('r') as f:
        configuration['reaction'] = yaml.safe_load(f)
    with (env_dir / 'reaction_sets.yaml').open('r') as f:
        configuration['reaction_set'] = yaml.safe_load(f)
    with (env_dir / 'namespaces.yaml').open('r') as f:
        configuration['namespace'] = yaml.safe_load(f)
    
    handler = f"http://{os.getenv('HOST')}:{os.getenv('PORT')}/configuration"
    headers = {'Content-Type': 'application/yaml'}
    data = yaml.dump(configuration)
    resp = requests.post(handler, headers=headers, data=data)
    logging.info(f'{resp} {resp.content}')
    assert resp.status_code == 200


if __name__ == '__main__':
    main()
