#!/usr/bin/env python3
import argparse
import logging
from pathlib import Path

import common

logging.basicConfig(level=logging.DEBUG)


def parse_args():
    parser = argparse.ArgumentParser(description='Implementation loader')
    parser.add_argument('impl_name', help='Implementation name (e.g. "mvp")')
    return parser.parse_args()

        
def on_impl(dir_path: Path, impl_dir_path: Path):
    common.clean_directory(dir_path)
    common.copy_directory(impl_dir_path, dir_path)


def main():
    args = parse_args()
    root = Path.cwd()
    assert root.is_dir()
    common.traverse(root, args.impl_name, on_impl)
    

if __name__ == '__main__':
    main()
