#!/usr/bin/env bash

set -e

DOCKER_COMPOSE_TMP="docker-compose.yaml.tmp.$RESOURCE"
${SCRIPTS_DIR}/patch_docker_compose --set-platform linux/x86_64 < docker-compose.yaml > $DOCKER_COMPOSE_TMP
docker-compose -f $DOCKER_COMPOSE_TMP build $SERVICES
docker-compose -f $DOCKER_COMPOSE_TMP push $SERVICES
rm $DOCKER_COMPOSE_TMP
