#!/usr/bin/env bash

set -e

ssh -o "StrictHostKeyChecking no" $SSH_USER@$SSH_HOST "mkdir -p $REMOTE_WORKDIR"

DOCKER_COMPOSE_TMP="docker-compose.yaml.tmp.$RESOURCE"
${SCRIPTS_DIR}/patch_docker_compose --unset-build --unset-depends-on < docker-compose.yaml > $DOCKER_COMPOSE_TMP
scp $DOCKER_COMPOSE_TMP $SSH_USER@$SSH_HOST:$REMOTE_WORKDIR/docker-compose.yaml
rm $DOCKER_COMPOSE_TMP

ln -sf .env.yacloud .env
scp $(realpath .env) $SSH_USER@$SSH_HOST:$REMOTE_WORKDIR/.env
